package com.iti.jets.reportingSystem.entity;
// Generated Jun 2, 2021, 9:20:41 PM by Hibernate Tools 6.0.0.Alpha2


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * BudgetActual generated by hbm2java
 */
@Entity
@Table(name="budget_actual"
    ,catalog="reportingsysschema"
)
public class BudgetActual  implements java.io.Serializable {


     private int id;
     private Date productionDate;
     private Double meleihaBudget;
     private Double meleihaActual;
     private Double meleihaPercentage;
     private Double agharActual;
     private Double agharBudget;
     private Double agharPercentage;
     private Double eastKanaysActual;
     private Double eastKanaysBudget;
     private Double eastKanysPercentage;
     private Double zarifActual;
     private Double zarifBudget;
     private Double zarifPercentage;
     private Double farasActual;
     private Double farasBudget;
     private Double farasPercentage;
     private Double ramlActual;
     private Double ramlBudget;
     private Double ramlPercentage;
     private Double westernDesertActual;
     private Double westernDesertBudget;
     private Double westernDesertPercentage;
     private Double ashrafiActual;
     private Double ashrafiBudget;
     private Double ashrafiPercentage;
     private Double agibaOilActual;
     private Double agibaOilBudget;
     private Double agibaOilPercentage;
     private Double salesGasActual;
     private Double salesGasBudget;
     private Double salesGasPercentage;
     private Double agibaBoEactual;
     private Double agibaBoEbudget;
     private Double agibaBoPercentage;

    public BudgetActual() {
    }

	
    public BudgetActual(int id) {
        this.id = id;
    }
    public BudgetActual(int id, Date productionDate, Double meleihaBudget, Double meleihaActual, Double meleihaPercentage, Double agharActual, Double agharBudget, Double agharPercentage, Double eastKanaysActual, Double eastKanaysBudget, Double eastKanysPercentage, Double zarifActual, Double zarifBudget, Double zarifPercentage, Double farasActual, Double farasBudget, Double farasPercentage, Double ramlActual, Double ramlBudget, Double ramlPercentage, Double westernDesertActual, Double westernDesertBudget, Double westernDesertPercentage, Double ashrafiActual, Double ashrafiBudget, Double ashrafiPercentage, Double agibaOilActual, Double agibaOilBudget, Double agibaOilPercentage, Double salesGasActual, Double salesGasBudget, Double salesGasPercentage, Double agibaBoEactual, Double agibaBoEbudget, Double agibaBoPercentage) {
       this.id = id;
       this.productionDate = productionDate;
       this.meleihaBudget = meleihaBudget;
       this.meleihaActual = meleihaActual;
       this.meleihaPercentage = meleihaPercentage;
       this.agharActual = agharActual;
       this.agharBudget = agharBudget;
       this.agharPercentage = agharPercentage;
       this.eastKanaysActual = eastKanaysActual;
       this.eastKanaysBudget = eastKanaysBudget;
       this.eastKanysPercentage = eastKanysPercentage;
       this.zarifActual = zarifActual;
       this.zarifBudget = zarifBudget;
       this.zarifPercentage = zarifPercentage;
       this.farasActual = farasActual;
       this.farasBudget = farasBudget;
       this.farasPercentage = farasPercentage;
       this.ramlActual = ramlActual;
       this.ramlBudget = ramlBudget;
       this.ramlPercentage = ramlPercentage;
       this.westernDesertActual = westernDesertActual;
       this.westernDesertBudget = westernDesertBudget;
       this.westernDesertPercentage = westernDesertPercentage;
       this.ashrafiActual = ashrafiActual;
       this.ashrafiBudget = ashrafiBudget;
       this.ashrafiPercentage = ashrafiPercentage;
       this.agibaOilActual = agibaOilActual;
       this.agibaOilBudget = agibaOilBudget;
       this.agibaOilPercentage = agibaOilPercentage;
       this.salesGasActual = salesGasActual;
       this.salesGasBudget = salesGasBudget;
       this.salesGasPercentage = salesGasPercentage;
       this.agibaBoEactual = agibaBoEactual;
       this.agibaBoEbudget = agibaBoEbudget;
       this.agibaBoPercentage = agibaBoPercentage;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="ProductionDate", length=10)
    public Date getProductionDate() {
        return this.productionDate;
    }
    
    public void setProductionDate(Date productionDate) {
        this.productionDate = productionDate;
    }

    
    @Column(name="meleihaBudget", precision=22, scale=0)
    public Double getMeleihaBudget() {
        return this.meleihaBudget;
    }
    
    public void setMeleihaBudget(Double meleihaBudget) {
        this.meleihaBudget = meleihaBudget;
    }

    
    @Column(name="meleihaActual", precision=22, scale=0)
    public Double getMeleihaActual() {
        return this.meleihaActual;
    }
    
    public void setMeleihaActual(Double meleihaActual) {
        this.meleihaActual = meleihaActual;
    }

    
    @Column(name="meleihaPercentage", precision=22, scale=0)
    public Double getMeleihaPercentage() {
        return this.meleihaPercentage;
    }
    
    public void setMeleihaPercentage(Double meleihaPercentage) {
        this.meleihaPercentage = meleihaPercentage;
    }

    
    @Column(name="agharActual", precision=22, scale=0)
    public Double getAgharActual() {
        return this.agharActual;
    }
    
    public void setAgharActual(Double agharActual) {
        this.agharActual = agharActual;
    }

    
    @Column(name="agharBudget", precision=22, scale=0)
    public Double getAgharBudget() {
        return this.agharBudget;
    }
    
    public void setAgharBudget(Double agharBudget) {
        this.agharBudget = agharBudget;
    }

    
    @Column(name="agharPercentage", precision=22, scale=0)
    public Double getAgharPercentage() {
        return this.agharPercentage;
    }
    
    public void setAgharPercentage(Double agharPercentage) {
        this.agharPercentage = agharPercentage;
    }

    
    @Column(name="eastKanaysActual", precision=22, scale=0)
    public Double getEastKanaysActual() {
        return this.eastKanaysActual;
    }
    
    public void setEastKanaysActual(Double eastKanaysActual) {
        this.eastKanaysActual = eastKanaysActual;
    }

    
    @Column(name="eastKanaysBudget", precision=22, scale=0)
    public Double getEastKanaysBudget() {
        return this.eastKanaysBudget;
    }
    
    public void setEastKanaysBudget(Double eastKanaysBudget) {
        this.eastKanaysBudget = eastKanaysBudget;
    }

    
    @Column(name="eastKanysPercentage", precision=22, scale=0)
    public Double getEastKanysPercentage() {
        return this.eastKanysPercentage;
    }
    
    public void setEastKanysPercentage(Double eastKanysPercentage) {
        this.eastKanysPercentage = eastKanysPercentage;
    }

    
    @Column(name="zarifActual", precision=22, scale=0)
    public Double getZarifActual() {
        return this.zarifActual;
    }
    
    public void setZarifActual(Double zarifActual) {
        this.zarifActual = zarifActual;
    }

    
    @Column(name="zarifBudget", precision=22, scale=0)
    public Double getZarifBudget() {
        return this.zarifBudget;
    }
    
    public void setZarifBudget(Double zarifBudget) {
        this.zarifBudget = zarifBudget;
    }

    
    @Column(name="zarifPercentage", precision=22, scale=0)
    public Double getZarifPercentage() {
        return this.zarifPercentage;
    }
    
    public void setZarifPercentage(Double zarifPercentage) {
        this.zarifPercentage = zarifPercentage;
    }

    
    @Column(name="farasActual", precision=22, scale=0)
    public Double getFarasActual() {
        return this.farasActual;
    }
    
    public void setFarasActual(Double farasActual) {
        this.farasActual = farasActual;
    }

    
    @Column(name="farasBudget", precision=22, scale=0)
    public Double getFarasBudget() {
        return this.farasBudget;
    }
    
    public void setFarasBudget(Double farasBudget) {
        this.farasBudget = farasBudget;
    }

    
    @Column(name="farasPercentage", precision=22, scale=0)
    public Double getFarasPercentage() {
        return this.farasPercentage;
    }
    
    public void setFarasPercentage(Double farasPercentage) {
        this.farasPercentage = farasPercentage;
    }

    
    @Column(name="ramlActual", precision=22, scale=0)
    public Double getRamlActual() {
        return this.ramlActual;
    }
    
    public void setRamlActual(Double ramlActual) {
        this.ramlActual = ramlActual;
    }

    
    @Column(name="ramlBudget", precision=22, scale=0)
    public Double getRamlBudget() {
        return this.ramlBudget;
    }
    
    public void setRamlBudget(Double ramlBudget) {
        this.ramlBudget = ramlBudget;
    }

    
    @Column(name="ramlPercentage", precision=22, scale=0)
    public Double getRamlPercentage() {
        return this.ramlPercentage;
    }
    
    public void setRamlPercentage(Double ramlPercentage) {
        this.ramlPercentage = ramlPercentage;
    }

    
    @Column(name="westernDesertActual", precision=22, scale=0)
    public Double getWesternDesertActual() {
        return this.westernDesertActual;
    }
    
    public void setWesternDesertActual(Double westernDesertActual) {
        this.westernDesertActual = westernDesertActual;
    }

    
    @Column(name="westernDesertBudget", precision=22, scale=0)
    public Double getWesternDesertBudget() {
        return this.westernDesertBudget;
    }
    
    public void setWesternDesertBudget(Double westernDesertBudget) {
        this.westernDesertBudget = westernDesertBudget;
    }

    
    @Column(name="westernDesertPercentage", precision=22, scale=0)
    public Double getWesternDesertPercentage() {
        return this.westernDesertPercentage;
    }
    
    public void setWesternDesertPercentage(Double westernDesertPercentage) {
        this.westernDesertPercentage = westernDesertPercentage;
    }

    
    @Column(name="ashrafiActual", precision=22, scale=0)
    public Double getAshrafiActual() {
        return this.ashrafiActual;
    }
    
    public void setAshrafiActual(Double ashrafiActual) {
        this.ashrafiActual = ashrafiActual;
    }

    
    @Column(name="ashrafiBudget", precision=22, scale=0)
    public Double getAshrafiBudget() {
        return this.ashrafiBudget;
    }
    
    public void setAshrafiBudget(Double ashrafiBudget) {
        this.ashrafiBudget = ashrafiBudget;
    }

    
    @Column(name="ashrafiPercentage", precision=22, scale=0)
    public Double getAshrafiPercentage() {
        return this.ashrafiPercentage;
    }
    
    public void setAshrafiPercentage(Double ashrafiPercentage) {
        this.ashrafiPercentage = ashrafiPercentage;
    }

    
    @Column(name="agibaOilActual", precision=22, scale=0)
    public Double getAgibaOilActual() {
        return this.agibaOilActual;
    }
    
    public void setAgibaOilActual(Double agibaOilActual) {
        this.agibaOilActual = agibaOilActual;
    }

    
    @Column(name="agibaOilBudget", precision=22, scale=0)
    public Double getAgibaOilBudget() {
        return this.agibaOilBudget;
    }
    
    public void setAgibaOilBudget(Double agibaOilBudget) {
        this.agibaOilBudget = agibaOilBudget;
    }

    
    @Column(name="agibaOilPercentage", precision=22, scale=0)
    public Double getAgibaOilPercentage() {
        return this.agibaOilPercentage;
    }
    
    public void setAgibaOilPercentage(Double agibaOilPercentage) {
        this.agibaOilPercentage = agibaOilPercentage;
    }

    
    @Column(name="salesGasActual", precision=22, scale=0)
    public Double getSalesGasActual() {
        return this.salesGasActual;
    }
    
    public void setSalesGasActual(Double salesGasActual) {
        this.salesGasActual = salesGasActual;
    }

    
    @Column(name="salesGasBudget", precision=22, scale=0)
    public Double getSalesGasBudget() {
        return this.salesGasBudget;
    }
    
    public void setSalesGasBudget(Double salesGasBudget) {
        this.salesGasBudget = salesGasBudget;
    }

    
    @Column(name="salesGasPercentage", precision=22, scale=0)
    public Double getSalesGasPercentage() {
        return this.salesGasPercentage;
    }
    
    public void setSalesGasPercentage(Double salesGasPercentage) {
        this.salesGasPercentage = salesGasPercentage;
    }

    
    @Column(name="agibaBoEActual", precision=22, scale=0)
    public Double getAgibaBoEactual() {
        return this.agibaBoEactual;
    }
    
    public void setAgibaBoEactual(Double agibaBoEactual) {
        this.agibaBoEactual = agibaBoEactual;
    }

    
    @Column(name="agibaBoEBudget", precision=22, scale=0)
    public Double getAgibaBoEbudget() {
        return this.agibaBoEbudget;
    }
    
    public void setAgibaBoEbudget(Double agibaBoEbudget) {
        this.agibaBoEbudget = agibaBoEbudget;
    }

    
    @Column(name="agibaBoPercentage", precision=22, scale=0)
    public Double getAgibaBoPercentage() {
        return this.agibaBoPercentage;
    }
    
    public void setAgibaBoPercentage(Double agibaBoPercentage) {
        this.agibaBoPercentage = agibaBoPercentage;
    }




}


