package com.iti.jets.reportingSystem.entity;
// Generated Jun 2, 2021, 9:20:41 PM by Hibernate Tools 6.0.0.Alpha2


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Field generated by hbm2java
 */
@Entity
@Table(name="field"
    ,catalog="reportingsysschema"
    , uniqueConstraints = {@UniqueConstraint(columnNames="field_code"), @UniqueConstraint(columnNames="field_name")} 
)
public class Field  implements java.io.Serializable {


     private int fieldId;
     private Concession concession;
     private String fieldName;
     private String fieldCode;
     private Set<Well> wells = new HashSet<Well>(0);

    public Field() {
    }

	
    public Field(int fieldId, Concession concession, String fieldName, String fieldCode) {
        this.fieldId = fieldId;
        this.concession = concession;
        this.fieldName = fieldName;
        this.fieldCode = fieldCode;
    }
    public Field(int fieldId, Concession concession, String fieldName, String fieldCode, Set<Well> wells) {
       this.fieldId = fieldId;
       this.concession = concession;
       this.fieldName = fieldName;
       this.fieldCode = fieldCode;
       this.wells = wells;
    }
   
     @Id 

    
    @Column(name="field_id", unique=true, nullable=false)
    public int getFieldId() {
        return this.fieldId;
    }
    
    public void setFieldId(int fieldId) {
        this.fieldId = fieldId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="concession_id", nullable=false)
    public Concession getConcession() {
        return this.concession;
    }
    
    public void setConcession(Concession concession) {
        this.concession = concession;
    }

    
    @Column(name="field_name", unique=true, nullable=false, length=80)
    public String getFieldName() {
        return this.fieldName;
    }
    
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName;
    }

    
    @Column(name="field_code", unique=true, nullable=false, length=45)
    public String getFieldCode() {
        return this.fieldCode;
    }
    
    public void setFieldCode(String fieldCode) {
        this.fieldCode = fieldCode;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="field")
    public Set<Well> getWells() {
        return this.wells;
    }
    
    public void setWells(Set<Well> wells) {
        this.wells = wells;
    }




}


