package com.iti.jets.reportingSystem.entity;
// Generated Jun 2, 2021, 9:20:41 PM by Hibernate Tools 6.0.0.Alpha2


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * LabMesurement generated by hbm2java
 */
@Entity
@Table(name="lab_mesurement"
    ,catalog="reportingsysschema"
)
public class LabMesurement  implements java.io.Serializable {


     private int id;
     private Well well;
     private Date date;
     private Long s1;
     private Long s2;
     private Long s3;
     private Long s4;
     private Long s5;
     private String remarks;

    public LabMesurement() {
    }

	
    public LabMesurement(int id, Well well) {
        this.id = id;
        this.well = well;
    }
    public LabMesurement(int id, Well well, Date date, Long s1, Long s2, Long s3, Long s4, Long s5, String remarks) {
       this.id = id;
       this.well = well;
       this.date = date;
       this.s1 = s1;
       this.s2 = s2;
       this.s3 = s3;
       this.s4 = s4;
       this.s5 = s5;
       this.remarks = remarks;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="wellId", nullable=false)
    public Well getWell() {
        return this.well;
    }
    
    public void setWell(Well well) {
        this.well = well;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date", length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    
    @Column(name="s1", precision=10, scale=0)
    public Long getS1() {
        return this.s1;
    }
    
    public void setS1(Long s1) {
        this.s1 = s1;
    }

    
    @Column(name="s2", precision=10, scale=0)
    public Long getS2() {
        return this.s2;
    }
    
    public void setS2(Long s2) {
        this.s2 = s2;
    }

    
    @Column(name="s3", precision=10, scale=0)
    public Long getS3() {
        return this.s3;
    }
    
    public void setS3(Long s3) {
        this.s3 = s3;
    }

    
    @Column(name="s4", precision=10, scale=0)
    public Long getS4() {
        return this.s4;
    }
    
    public void setS4(Long s4) {
        this.s4 = s4;
    }

    
    @Column(name="s5", precision=10, scale=0)
    public Long getS5() {
        return this.s5;
    }
    
    public void setS5(Long s5) {
        this.s5 = s5;
    }

    
    @Column(name="remarks", length=1000)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


