package com.iti.jets.reportingSystem.entity;
// Generated Jun 2, 2021, 9:20:41 PM by Hibernate Tools 6.0.0.Alpha2


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProductionGeneralInfo generated by hbm2java
 */
@Entity
@Table(name="production_general_info"
    ,catalog="reportingsysschema"
)
public class ProductionGeneralInfo  implements java.io.Serializable {


     private int id;
     private Well well;
     private Date initialProdDate;
     private String initialType;
     private String initialProduct;
     private String initialLiftType;
     private String initStatus;
     private String monitoringSystem;
     private Date currentWellTypeDate;
     private String currentWellType;
     private String currentProduct;
     private String currentStatus;
     private Integer runTime;
     private String currentLiftType;
     private Date currentLiftTypeDate;
     private String powerSourceType;
     private String powerSource;
     private String processionPlant;

    public ProductionGeneralInfo() {
    }

	
    public ProductionGeneralInfo(int id, Well well) {
        this.id = id;
        this.well = well;
    }
    public ProductionGeneralInfo(int id, Well well, Date initialProdDate, String initialType, String initialProduct, String initialLiftType, String initStatus, String monitoringSystem, Date currentWellTypeDate, String currentWellType, String currentProduct, String currentStatus, Integer runTime, String currentLiftType, Date currentLiftTypeDate, String powerSourceType, String powerSource, String processionPlant) {
       this.id = id;
       this.well = well;
       this.initialProdDate = initialProdDate;
       this.initialType = initialType;
       this.initialProduct = initialProduct;
       this.initialLiftType = initialLiftType;
       this.initStatus = initStatus;
       this.monitoringSystem = monitoringSystem;
       this.currentWellTypeDate = currentWellTypeDate;
       this.currentWellType = currentWellType;
       this.currentProduct = currentProduct;
       this.currentStatus = currentStatus;
       this.runTime = runTime;
       this.currentLiftType = currentLiftType;
       this.currentLiftTypeDate = currentLiftTypeDate;
       this.powerSourceType = powerSourceType;
       this.powerSource = powerSource;
       this.processionPlant = processionPlant;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="wellID", nullable=false)
    public Well getWell() {
        return this.well;
    }
    
    public void setWell(Well well) {
        this.well = well;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="initialProdDate", length=10)
    public Date getInitialProdDate() {
        return this.initialProdDate;
    }
    
    public void setInitialProdDate(Date initialProdDate) {
        this.initialProdDate = initialProdDate;
    }

    
    @Column(name="initialType", length=19)
    public String getInitialType() {
        return this.initialType;
    }
    
    public void setInitialType(String initialType) {
        this.initialType = initialType;
    }

    
    @Column(name="initialProduct", length=14)
    public String getInitialProduct() {
        return this.initialProduct;
    }
    
    public void setInitialProduct(String initialProduct) {
        this.initialProduct = initialProduct;
    }

    
    @Column(name="initialLiftType", length=11)
    public String getInitialLiftType() {
        return this.initialLiftType;
    }
    
    public void setInitialLiftType(String initialLiftType) {
        this.initialLiftType = initialLiftType;
    }

    
    @Column(name="initStatus", length=9)
    public String getInitStatus() {
        return this.initStatus;
    }
    
    public void setInitStatus(String initStatus) {
        this.initStatus = initStatus;
    }

    
    @Column(name="monitoringSystem", length=5)
    public String getMonitoringSystem() {
        return this.monitoringSystem;
    }
    
    public void setMonitoringSystem(String monitoringSystem) {
        this.monitoringSystem = monitoringSystem;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="currentWellTypeDate", length=10)
    public Date getCurrentWellTypeDate() {
        return this.currentWellTypeDate;
    }
    
    public void setCurrentWellTypeDate(Date currentWellTypeDate) {
        this.currentWellTypeDate = currentWellTypeDate;
    }

    
    @Column(name="currentWellType", length=19)
    public String getCurrentWellType() {
        return this.currentWellType;
    }
    
    public void setCurrentWellType(String currentWellType) {
        this.currentWellType = currentWellType;
    }

    
    @Column(name="currentProduct", length=14)
    public String getCurrentProduct() {
        return this.currentProduct;
    }
    
    public void setCurrentProduct(String currentProduct) {
        this.currentProduct = currentProduct;
    }

    
    @Column(name="currentStatus", length=9)
    public String getCurrentStatus() {
        return this.currentStatus;
    }
    
    public void setCurrentStatus(String currentStatus) {
        this.currentStatus = currentStatus;
    }

    
    @Column(name="runTime")
    public Integer getRunTime() {
        return this.runTime;
    }
    
    public void setRunTime(Integer runTime) {
        this.runTime = runTime;
    }

    
    @Column(name="currentLiftType", length=11)
    public String getCurrentLiftType() {
        return this.currentLiftType;
    }
    
    public void setCurrentLiftType(String currentLiftType) {
        this.currentLiftType = currentLiftType;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="currentLiftTypeDate", length=10)
    public Date getCurrentLiftTypeDate() {
        return this.currentLiftTypeDate;
    }
    
    public void setCurrentLiftTypeDate(Date currentLiftTypeDate) {
        this.currentLiftTypeDate = currentLiftTypeDate;
    }

    
    @Column(name="powerSourceType", length=16)
    public String getPowerSourceType() {
        return this.powerSourceType;
    }
    
    public void setPowerSourceType(String powerSourceType) {
        this.powerSourceType = powerSourceType;
    }

    
    @Column(name="powerSource", length=45)
    public String getPowerSource() {
        return this.powerSource;
    }
    
    public void setPowerSource(String powerSource) {
        this.powerSource = powerSource;
    }

    
    @Column(name="processionPlant", length=9)
    public String getProcessionPlant() {
        return this.processionPlant;
    }
    
    public void setProcessionPlant(String processionPlant) {
        this.processionPlant = processionPlant;
    }




}


