package com.iti.jets.reportingSystem.entity;
// Generated Jun 2, 2021, 9:20:41 PM by Hibernate Tools 6.0.0.Alpha2


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ShutinType generated by hbm2java
 */
@Entity
@Table(name="shutin_type"
    ,catalog="reportingsysschema"
)
public class ShutinType  implements java.io.Serializable {


     private int id;
     private String description;
     private Set<ShutinTypeLevel2> shutinTypeLevel2s = new HashSet<ShutinTypeLevel2>(0);

    public ShutinType() {
    }

	
    public ShutinType(int id, String description) {
        this.id = id;
        this.description = description;
    }
    public ShutinType(int id, String description, Set<ShutinTypeLevel2> shutinTypeLevel2s) {
       this.id = id;
       this.description = description;
       this.shutinTypeLevel2s = shutinTypeLevel2s;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="description", nullable=false, length=100)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="shutinType")
    public Set<ShutinTypeLevel2> getShutinTypeLevel2s() {
        return this.shutinTypeLevel2s;
    }
    
    public void setShutinTypeLevel2s(Set<ShutinTypeLevel2> shutinTypeLevel2s) {
        this.shutinTypeLevel2s = shutinTypeLevel2s;
    }




}


