package com.iti.jets.reportingSystem.entity;
// Generated Jun 2, 2021, 9:20:41 PM by Hibernate Tools 6.0.0.Alpha2


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * WellGeneralInfo generated by hbm2java
 */
@Entity
@Table(name="well_general_info"
    ,catalog="reportingsysschema"
)
public class WellGeneralInfo  implements java.io.Serializable {


     private int id;
     private Well well;
     private String subCompanyName;
     private String locationName;
     private String areaName;
     private String leaseName;
     private String boreName;
     private Double xcord;
     private Double ycord;
     private Double lat;
     private Double long_;

    public WellGeneralInfo() {
    }

	
    public WellGeneralInfo(int id, Well well) {
        this.id = id;
        this.well = well;
    }
    public WellGeneralInfo(int id, Well well, String subCompanyName, String locationName, String areaName, String leaseName, String boreName, Double xcord, Double ycord, Double lat, Double long_) {
       this.id = id;
       this.well = well;
       this.subCompanyName = subCompanyName;
       this.locationName = locationName;
       this.areaName = areaName;
       this.leaseName = leaseName;
       this.boreName = boreName;
       this.xcord = xcord;
       this.ycord = ycord;
       this.lat = lat;
       this.long_ = long_;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="wellId", nullable=false)
    public Well getWell() {
        return this.well;
    }
    
    public void setWell(Well well) {
        this.well = well;
    }

    
    @Column(name="subCompanyName", length=100)
    public String getSubCompanyName() {
        return this.subCompanyName;
    }
    
    public void setSubCompanyName(String subCompanyName) {
        this.subCompanyName = subCompanyName;
    }

    
    @Column(name="locationName", length=8)
    public String getLocationName() {
        return this.locationName;
    }
    
    public void setLocationName(String locationName) {
        this.locationName = locationName;
    }

    
    @Column(name="areaName", length=100)
    public String getAreaName() {
        return this.areaName;
    }
    
    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    
    @Column(name="leaseName", length=100)
    public String getLeaseName() {
        return this.leaseName;
    }
    
    public void setLeaseName(String leaseName) {
        this.leaseName = leaseName;
    }

    
    @Column(name="boreName", length=100)
    public String getBoreName() {
        return this.boreName;
    }
    
    public void setBoreName(String boreName) {
        this.boreName = boreName;
    }

    
    @Column(name="xCord", precision=22, scale=0)
    public Double getXcord() {
        return this.xcord;
    }
    
    public void setXcord(Double xcord) {
        this.xcord = xcord;
    }

    
    @Column(name="yCord", precision=22, scale=0)
    public Double getYcord() {
        return this.ycord;
    }
    
    public void setYcord(Double ycord) {
        this.ycord = ycord;
    }

    
    @Column(name="lat", precision=22, scale=0)
    public Double getLat() {
        return this.lat;
    }
    
    public void setLat(Double lat) {
        this.lat = lat;
    }

    
    @Column(name="long", precision=22, scale=0)
    public Double getLong_() {
        return this.long_;
    }
    
    public void setLong_(Double long_) {
        this.long_ = long_;
    }




}


